PozoristeNaDlanu2021/PozoristeNaDlanu2021/Biletarnik/Controllers/RepertoarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Biletarnik.Models;
using Biletarnik.Models.DAO;
using MySql.Data.MySqlClient;
namespace Biletarnik.Controllers
{
    public class RepertoarController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            
            if (Session["UserID"] != null)
            {
                Debug.WriteLine(Session["UserID"].ToString());
            }
            else
            {
                Debug.WriteLine("null");
            }
            List<PredstavaNaRepertoaru> predstave = new DAOFactoryImpl().CreatePredstavaNaRepertoaruDAO().getAll();

            return View(predstave);
        }
        public ActionResult RezervacijePredstave(int? id)
        {
            Debug.WriteLine(id + " kao ide prssssssss");
            List<Rezervacija> rezervacije= new DAOFactoryImpl().CreateRezervacijaDAO().rezervacijePredstave(id);
            return View(rezervacije);
        }
        public ActionResult SveBuduceRezervacije(string search)
        {
            List<Rezervacija> rezervacije = new List<Rezervacija>();
            if (search == null || search.Equals(""))
            {
                rezervacije = new DAOFactoryImpl().CreateRezervacijaDAO().rezervacijePredstave(-1);
            }
            else
            {
                rezervacije = new DAOFactoryImpl().CreateRezervacijaDAO().rezervacijeOdredjenogKorisnika(-1,search);
            }
            return View(rezervacije);
        }
    }
}

PozoristeNaDlanu2021/PozoristeNaDlanu2021/Biletarnik/Views/Repertoar/Index.cshtml
@model IEnumerable<Biletarnik.Models.PredstavaNaRepertoaru>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/_LayoutPage1.cshtml";
}
<section class="w3l-pricinghny">
    <div class="pricing-inner-info py-5">
        <div class="container py-lg-4">
            <div style="margin: 8px auto; display: block; text-align:center;">

                <!---728x90--->


            </div>
            <!--/pricing-info-grids-->
            @foreach (var item in Model)
            {
                <div class="pricing-info-grids">
                    <div class="price-box">
                        <div class="grid grid-column-2">
                            <div class="column">
                                <a class="title">@item.naziv</a>
                            </div>
                            <div class="column text-lg-center">
                                <p class="price-title">@item.vrijemeOdrzavanja</p>
                            </div>
                            <div class="column price-number text-md-right">
                                <h3 class="pricing">
                                    @item.cijena<sup class="pri1">KM</sup>
                                </h3>
                            </div>
                            <div class="column price-number text-md-right">
                                <a href="/Rezervacija/Index/@item.id"><button class="btn read-button">Rezervisi</button></a>
                                <a href="/Repertoar/RezervacijePredstave/@item.id" class="btn read-button">Rezervisano</a>
                                
                            </div>
                        </div>
                    </div>
                    <!--/box-->
                    <!--/box-->
                    <!--/box-->

                </div>
            }
            <!--/pricing-info-grids-->
        </div>
    </div>
</section>
<!--//pricing-->
<div style="margin: 8px auto; display: block; text-align:center;">

    <!---728x90--->

</div>

PozoristeNaDlanu2021/PozoristeNaDlanu2021/Biletarnik/Views/Repertoar/RezervacijePredstave.cshtml
@model IEnumerable<Biletarnik.Models.Rezervacija>

@{
    ViewBag.Title = "RezervacijePredstave";
    Layout = "~/Views/_LayoutPage1.cshtml";
}


<br />
<br />
<h2>RezervacijePredstave</h2>

<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.brojKarata)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idPredstaveNaRepertoaru)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naslovPredstave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idKorisnik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sjedista)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.placeno)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                
                @Html.DisplayFor(modelItem => item.brojKarata)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idPredstaveNaRepertoaru)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.naslovPredstave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idKorisnik)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sjedista)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.placeno)
            </td>
            <td>
                <a href="/Rezervacija/KupiRezervaciju/@item.idRezervacija"><button class="btn read-button">Kupi</button></a>
                <a href="/Rezervacija/ObrisiRezervaciju/@item.idRezervacija"><button class="btn read-button">Izbrisi</button></a>

            </td>
        </tr>
    }

</table>

PozoristeNaDlanu2021/PozoristeNaDlanu2021/Biletarnik/Views/Repertoar/SveBuduceRezervacije.cshtml
@model IEnumerable<Biletarnik.Models.Rezervacija>

@{
    ViewBag.Title = "SveBuduceRezervacije";
    Layout = "~/Views/_LayoutPage1.cshtml";
}

<br />
<br />
<h2>SveBuduceRezervacije</h2>
<br />
@using (Html.BeginForm("SveBuduceRezervacije", "Repertoar", FormMethod.Get))
{
    //the following are search options

    <b>  Pretraga rezervacija po username-u       </b>

    @Html.TextBox("search")
    <input type="submit" name="submit" value="Search" />
}
<br />
<br />
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.brojKarata)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.idPredstaveNaRepertoaru)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.naslovPredstave)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.username)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sjedista)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.placeno)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.brojKarata)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.idPredstaveNaRepertoaru)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.naslovPredstave)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sjedista)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.placeno)
            </td>
            <td>
                <a href="/Rezervacija/KupiRezervaciju/@item.idRezervacija"><button class="btn read-button">Kupi</button></a>
                <a href="/Rezervacija/ObrisiRezervaciju/@item.idRezervacija"><button class="btn read-button">Izbrisi</button></a>

            </td>
        </tr>
    }

</table>